[project]
name = "bytepairencoding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beartype>=0.20.2",
    "numpy>=2.2.5",
    "pybind11>=2.13.6",
    "regex>=2024.11.6",
]
